version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    ports:
      - "3000:5173"  # maps localhost:3000 to container:5173
    depends_on:
      - backend
